version: "3.8"

services:
  backend:
    build: ./backend
    command: ./wait-for-it.sh postgres:5432 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    environment:
      DB_ENGINE: ${DB_ENGINE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: postgres
      SECRET_KEY: ${SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - redis
      - postgres
    restart: on-failure
    volumes:
      - .:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:8080"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
