# Generated by Django 5.1.6 on 2025-02-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished'), ('errored', 'Errored'), ('killed', 'Killed')], default='in_progress', max_length=20)),
                ('ai_response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
