# Generated by Django 5.1.6 on 2025-02-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='ai_action_log',
            field=models.CharField(choices=[('init-agent-flow', 'Initializing Agent Flow'), ('get-message-history', 'Get previous messages'), ('scene', 'Scene Architecture Determination'), ('rethink', 'Rethinking'), ('agent-thinks', 'Agent thinks now'), ('agent-observes', 'Agent observes now'), ('agent-decides-action', 'Agent action decision'), ('final-answer', 'The final answer is cooking')], default='init-agent-flow', max_length=20),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='scene',
            field=models.CharField(choices=[('None', 'Agents have not yet decided the scene'), ('G1', 'Direct-Structured Goal Scene'), ('G2', 'Values-Deep-Dive Goal Scene'), ('G3', 'Strategic-Analytical Goal Scene'), ('R1', 'Systematic-Assessment Reality Scene'), ('R2', 'Emotional-Landscape Reality Scene'), ('R3', 'Systems-Thinking Reality Scene'), ('O1', 'Strategic-Analytical Opportunity Scene'), ('O2', 'Solution-Engineering Opportunity Scene'), ('O3', 'Creative-Generative Opportunity Scene'), ('W1', 'Action-Planning Way Forward Scene'), ('W2', 'Commitment-Building Way Forward Scene'), ('W3', 'Integration-Focused Way Forward Scene')], default='None', max_length=20),
        ),
    ]
