# Generated by Django 5.1.6 on 2025-02-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_conversationmessage_ai_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='user',
        ),
    ]
